dist: bionic
language: php

php:
  - '7.2'

install:
  - composer install
  - yarn install --frozen-lockfile

script:
  - vendor/bin/php-cs-fixer fix --dry-run --diff
  - php artisan code:analyse
  - yarn lint
