dist: bionic
language: php

env:
  - APP_ENV=testing

php:
  - '7.2'

install:
  - composer install
  - yarn install --frozen-lockfile

script:
  # Lint source files
  - vendor/bin/php-cs-fixer fix --dry-run --diff
  - php artisan code:analyse --level 7
  - yarn run lint

  # Build assets and generate API documentation
  - yarn run prod
  - yarn run doc

  # Run tests
  - vendor/bin/phpunit
