dist: bionic
language: php

env:
  - APP_ENV=testing

php:
  - '7.3'

services:
  - mysql

install:
  - composer install
  - yarn install --frozen-lockfile
  - php artisan config:cache
  - php artisan route:cache

script:
  # Lint source files
  - vendor/bin/php-cs-fixer fix --dry-run --diff
  - vendor/bin/phpstan analyse
  - yarn run lint

  # Build assets and generate API documentation
  - yarn run prod
  - yarn run doc

  # Run tests and upload code coverage results
  - php artisan db:create
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - bash <(curl -s https://codecov.io/bash)
