version: "3.8"
services:

  composer:
    image: composer:2.0
    working_dir: /app
    volumes:
      - ./:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: composer install --ignore-platform-reqs --no-scripts

  app:
    build:
      target: dev
    restart: "no"
    depends_on:
      - composer
      - db
    volumes:
      - ./:/app
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

  nginx:
    image: nginx:1.19-alpine
    environment:
      VIRTUAL_HOST: testing.local
    restart: "no"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public:ro

  node:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "yarn install && yarn run watch"
